version: '3.8'

services:
  compliance-service:
    build: ./compliance-service
    container_name: compliance-service
    ports:
      - "8080:8080"
    environment:
      - COMPLIANCE_PORT=8080
    volumes:
      - ./compliance-service/database:/app/database

  payment-service:
    build: ./payment-service
    container_name: payment-service
    ports:
      - "8081:8081"
    environment:
      - PAYMENT_PORT=8081
      - COMPLIANCE_SERVICE_URL=http://compliance-service:8080
    depends_on:
      - compliance-service
