// Code generated by MockGen. DO NOT EDIT.
// Source: compliance_service.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockComplianceService is a mock of ComplianceService interface.
type MockComplianceService struct {
	ctrl     *gomock.Controller
	recorder *MockComplianceServiceMockRecorder
}

// MockComplianceServiceMockRecorder is the mock recorder for MockComplianceService.
type MockComplianceServiceMockRecorder struct {
	mock *MockComplianceService
}

// NewMockComplianceService creates a new mock instance.
func NewMockComplianceService(ctrl *gomock.Controller) *MockComplianceService {
	mock := &MockComplianceService{ctrl: ctrl}
	mock.recorder = &MockComplianceServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockComplianceService) EXPECT() *MockComplianceServiceMockRecorder {
	return m.recorder
}

// CheckComplianceStatus mocks base method.
func (m *MockComplianceService) CheckComplianceStatus(userID, cardID int64) (bool, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckComplianceStatus", userID, cardID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CheckComplianceStatus indicates an expected call of CheckComplianceStatus.
func (mr *MockComplianceServiceMockRecorder) CheckComplianceStatus(userID, cardID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckComplianceStatus", reflect.TypeOf((*MockComplianceService)(nil).CheckComplianceStatus), userID, cardID)
}

// ReportStolenCards mocks base method.
func (m *MockComplianceService) ReportStolenCards(userName, secretCode string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReportStolenCards", userName, secretCode)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReportStolenCards indicates an expected call of ReportStolenCards.
func (mr *MockComplianceServiceMockRecorder) ReportStolenCards(userName, secretCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReportStolenCards", reflect.TypeOf((*MockComplianceService)(nil).ReportStolenCards), userName, secretCode)
}
